DROP TABLE IF EXISTS settlements;
DROP TABLES IF EXISTS expense_splits;
DROP TABLE IF EXISTS expenses;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS household_members;
DROP TABLE IF EXISTS households;
DROP TABLE IF EXISTS users; 

CREATE TABLE users (
    id INT UNSIGNED AUTO INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR (255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT8STAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 